### token
POST {{baseUrl}}/api/auth/token
Content-Type: application/json


{
  "username": "user",
  "password": "pass"
}

> {%
    client.global.set("token", response.body.token);
%}


### create template
POST {{baseUrl}}/api/box
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

{
  "payload": {
    "service": "widget-x",
    "stage": {
      "development": {
        "template": {
          "name": "task_definition.json",
          "value": "ewogICAiRU5WXzEiOiAie3dpZGdldC14LmRldmVsb3BtZW50LmtleX0iLAogICAiRU5WXzIiOiAie3dpZGdldC14LmRldmVsb3BtZW50LmRlYnVnfSIsCiAgICJHTE9CQUxfU0VSVklDRSI6ICJ7d2lkZ2V0LXguc2VudHJ5fSIsCiAgICJkb21haW4iOiAie3ByaXZhdGUtZG9tYWlufSIsCiAgICJ2ZXJzaW9uIjogIjEiCn0K"
        }
      }
    }
  }
}


### get all boxes
GET {{baseUrl}}/api/box
Authorization: Bearer {{token}}
Content-Type: application/json


### retrieve secret value
GET {{baseUrl}}/api/entry/secret-value?v=/global/example/unique-key7
Authorization: Bearer {{token}}
Content-Type: application/json


### check exist template
HEAD {{baseUrl}}/api/box/widget-x/development/task_definition.json
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### get template
GET {{baseUrl}}/api/box/example/development/task_definition.json
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### vars template
GET {{baseUrl}}/api/box/example/development/task_definition.json/vars
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### build template
GET {{baseUrl}}/api/box/crossborder-api/development/task_definition.json/build
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### create
POST {{baseUrl}}/api/entry
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

[
  {"key": "test/qa/var001", "value": "test.com"}
]


### testing create
POST {{baseUrl}}/api/entry
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json

[
  {
    "key": "/global/example/debub",
    "value": "False"
  },
  {
    "key": "/global/example/unique-key7",
    "value": "secret-1234",
    "secure": true
  }
]


### Get key
GET {{baseUrl}}/api/entry/key?v=global/example/unique-key7
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json


### Get prefix
GET {{baseUrl}}/api/entry/prefix?v=global/example/
Content-Type: application/json
Authorization: Basic {{user}} {{pass}}


### list tracking history
GET {{baseUrl}}/api/track/key?v=global/example/unique-key6
Content-Type: application/json
Authorization: Basic {{user}} {{pass}}



### all environments
GET {{baseUrl}}/api/static/environments
Content-Type: application/json
Authorization: Basic {{user}} {{pass}}

### Delete key
DELETE {{baseUrl}}/api/entry/key?v=widget-x/development3
Authorization: Basic {{user}} {{pass}}
Content-Type: application/json
